"""Add language and timezone to guild_settings

Revision ID: 129a2e7476c4
Revises: ad3d7d861c7b
Create Date: 2023-10-14 17:49:23.236403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '129a2e7476c4'
down_revision = 'ad3d7d861c7b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('guild_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_settings', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
