"""Add users table

Revision ID: 30f50c56d57c
Revises: f7d2070e79df
Create Date: 2023-04-18 11:41:21.459395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "30f50c56d57c"
down_revision = "f7d2070e79df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("global_name", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=64), nullable=True),
        sa.Column("avatar", sa.String(length=128), nullable=True),
        sa.Column("discriminator", sa.String(length=4), nullable=True),
        sa.Column("public_flags", sa.Integer(), nullable=True),
        sa.Column("flags", sa.Integer(), nullable=True),
        sa.Column("banner", sa.String(length=128), nullable=True),
        sa.Column("banner_color", sa.String(length=7), nullable=True),
        sa.Column("accent_color", sa.Integer(), nullable=True),
        sa.Column("locale", sa.String(length=2), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=True),
        sa.Column("premium_type", sa.Integer(), nullable=True),
        sa.Column("avatar_decoration", sa.String(length=128), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
