"""Add guild_settings table

Revision ID: 4bb4b7f17296
Revises: 541fb5d6e8c7
Create Date: 2023-07-06 18:42:15.840298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bb4b7f17296'
down_revision = '541fb5d6e8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birthdays_channel_id', sa.String(length=300), nullable=True),
    sa.Column('answers_channel_id', sa.String(length=300), nullable=True),
    sa.Column('holiday_channel_id', sa.String(length=300), nullable=True),
    sa.Column('guild_id', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guild_settings')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_guild_settings_guild_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_settings')
    # ### end Alembic commands ###
