"""Add drawer table

Revision ID: 517a33b57a15
Revises: 
Create Date: 2023-03-06 10:50:22.495692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "517a33b57a15"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drawers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "draw_type",
            sa.Enum("writing", "music", "painting", name="enum_drawer_type"),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(length=300), nullable=False),
        sa.Column("guild_id", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drawers")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drawers")
    op.execute("""DROP TYPE enum_drawer_type""")
    # ### end Alembic commands ###
