"""Add channel_id field to birthdays table

Revision ID: 541fb5d6e8c7
Revises: 4b95413a2d94
Create Date: 2023-07-03 19:56:17.270639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "541fb5d6e8c7"
down_revision = "4b95413a2d94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("birthdays", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("channel_id", sa.String(length=300), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("birthdays", schema=None) as batch_op:
        batch_op.drop_column("channel_id")

    # ### end Alembic commands ###
