"""Add wishes to birthdays_config table

Revision ID: 69a577cbd831
Revises: 129a2e7476c4
Create Date: 2023-11-01 18:21:44.172969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69a577cbd831'
down_revision = '129a2e7476c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birthday_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wishes_singular', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('wishes_plural', postgresql.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('birthday_configs', schema=None) as batch_op:
        batch_op.drop_column('wishes_plural')
        batch_op.drop_column('wishes_singular')

    # ### end Alembic commands ###
