"""Add answers table

Revision ID: 81d6c030ffa4
Revises: 16be16a7b5b7
Create Date: 2023-03-07 10:15:28.029995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "81d6c030ffa4"
down_revision = "16be16a7b5b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("why_answers", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("does_answers", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("when_answers", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "what_do_you_think_answers", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column("how_answers", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("who_answers", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("what_answers", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("what_is_answers", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("guild_id", sa.String(length=300), nullable=False),
        sa.Column("channel_id", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answers")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answers")
    # ### end Alembic commands ###
