"""Add drawers table

Revision ID: 828bde61914b
Revises: 
Create Date: 2023-03-05 13:53:05.535403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828bde61914b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_type', sa.Enum('WRITING', 'MUSIC', 'PAINTING', name='drawer_type'), nullable=False),
    sa.Column('user_id', sa.String(length=300), nullable=False),
    sa.Column('guild_id', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drawers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drawers')
    op.execute("""DROP TYPE drawer_type""")
    # ### end Alembic commands ###
