"""Granulate guild settings

Revision ID: ad3d7d861c7b
Revises: cc20f8bc64e9
Create Date: 2023-10-07 12:03:40.954359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ad3d7d861c7b"
down_revision = "cc20f8bc64e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answer_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("answers_handle_channel_id", sa.String(length=300), nullable=True),
        sa.Column("guild_id", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answer_configs")),
        sa.UniqueConstraint("guild_id", name=op.f("uq_answer_configs_guild_id")),
    )
    op.create_table(
        "birthday_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "birthdays_announcement_channel_id", sa.String(length=300), nullable=True
        ),
        sa.Column("birthdays_handle_channel_id", sa.String(length=300), nullable=True),
        sa.Column("guild_id", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_birthday_configs")),
        sa.UniqueConstraint("guild_id", name=op.f("uq_birthday_configs_guild_id")),
    )
    op.create_table(
        "holiday_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "holiday_announcement_channel_id", sa.String(length=300), nullable=True
        ),
        sa.Column("guild_id", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holiday_configs")),
        sa.UniqueConstraint("guild_id", name=op.f("uq_holiday_configs_guild_id")),
    )
    with op.batch_alter_table("draw_configs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "graphic_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "draw_challenges_writing_handle_channel_id",
                sa.String(length=300),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "draw_challenges_graphic_handle_channel_id",
                sa.String(length=300),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "draw_challenges_music_handle_channel_id",
                sa.String(length=300),
                nullable=True,
            )
        )
        batch_op.drop_column("painting_config")

    with op.batch_alter_table("guild_settings", schema=None) as batch_op:
        batch_op.drop_column("draw_challenges_music_handle_channel_id")
        batch_op.drop_column("birthdays_announcement_channel_id")
        batch_op.drop_column("answers_channel_id")
        batch_op.drop_column("draw_challenges_graphic_handle_channel_id")
        batch_op.drop_column("draw_challenges_writing_handle_channel_id")
        batch_op.drop_column("holiday_announcement_channel_id")
        batch_op.drop_column("birthdays_handle_channel_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guild_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "birthdays_handle_channel_id",
                sa.VARCHAR(length=300),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "holiday_announcement_channel_id",
                sa.VARCHAR(length=300),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "draw_challenges_writing_handle_channel_id",
                sa.VARCHAR(length=300),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "draw_challenges_graphic_handle_channel_id",
                sa.VARCHAR(length=300),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "answers_channel_id",
                sa.VARCHAR(length=300),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "birthdays_announcement_channel_id",
                sa.VARCHAR(length=300),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "draw_challenges_music_handle_channel_id",
                sa.VARCHAR(length=300),
                autoincrement=False,
                nullable=True,
            )
        )

    with op.batch_alter_table("draw_configs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "painting_config",
                postgresql.JSONB(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("draw_challenges_music_handle_channel_id")
        batch_op.drop_column("draw_challenges_graphic_handle_channel_id")
        batch_op.drop_column("draw_challenges_writing_handle_channel_id")
        batch_op.drop_column("graphic_config")

    op.drop_table("holiday_configs")
    op.drop_table("birthday_configs")
    op.drop_table("answer_configs")
    # ### end Alembic commands ###
