"""Refactor channel ids naming

Revision ID: cc20f8bc64e9
Revises: ff8ee392da5c
Create Date: 2023-09-30 19:11:17.691163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cc20f8bc64e9"
down_revision = "ff8ee392da5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guild_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "birthdays_handle_channel_id", sa.String(length=300), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "draw_challenges_graphic_handle_channel_id",
                sa.String(length=300),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "draw_challenges_music_handle_channel_id",
                sa.String(length=300),
                nullable=True,
            )
        )
        batch_op.alter_column(
            "draw_challenges_channel_id",
            new_column_name="draw_challenges_writing_handle_channel_id",
        )
        batch_op.alter_column(
            "holiday_channel_id", new_column_name="holiday_announcement_channel_id"
        )
        batch_op.alter_column(
            "birthdays_channel_id", new_column_name="birthdays_announcement_channel_id"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guild_settings", schema=None) as batch_op:
        batch_op.drop_column("draw_challenges_music_handle_channel_id")
        batch_op.drop_column("draw_challenges_graphic_handle_channel_id")
        batch_op.drop_column("birthdays_handle_channel_id")
        batch_op.drop_column("birthdays_announcement_channel_id")
        batch_op.alter_column(
            "draw_challenges_writing_handle_channel_id",
            new_column_name="draw_challenges_channel_id",
        )
        batch_op.alter_column(
            "holiday_announcement_channel_id", new_column_name="holiday_channel_id"
        )
        batch_op.alter_column(
            "birthdays_channel_id", new_column_name="birthdays_announcement_channel_id"
        )

    # ### end Alembic commands ###
